import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
const html = readFileSync(new URL('../dist-demo/index.html', import.meta.url));
const srv = createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(html); }).listen(4176);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } });
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4176/#/login');
await p.fill('#login-email', 'maya.raman@demo.csqa.test'); await p.fill('#login-password', 'Demo@2026'); await p.click('button[type=submit]');
await p.waitForSelector('main h1');
await p.goto('http://localhost:4176/#/admin/emails'); await p.waitForSelector('text=Email preview');
await p.waitForTimeout(800);
console.log('subject', await p.locator('text=Subject:').locator('..').textContent());
const btn = p.locator('button:has-text("not yet emailed")'); console.log('button', await btn.textContent());
await btn.click(); await p.click('[role=dialog] button:has-text("Send")'); await p.waitForTimeout(1200);
console.log('sent pills', await p.locator('text=Sent').count(), 'not sent', await p.locator('td >> text=Not sent').count());
await p.screenshot({ path: 'e2e/shots/emails.png', fullPage: true });
await p.goto('http://localhost:4176/#/admin/teams'); await p.waitForSelector('text=Import CAM');
console.log('teams ok; errors', errs);
await b.close(); srv.close();
