// Local review mode with the REAL sheet export (kept inside this sandbox only).
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
const root = new URL('../dist-local/', import.meta.url).pathname;
const srv = createServer((q, r) => { let p = join(root, decodeURIComponent(q.url.split('?')[0])); if (!existsSync(p) || p.endsWith('/')) p = join(root, 'index.html');
  r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[extname(p)] ?? 'application/octet-stream' }); r.end(readFileSync(p)); }).listen(4177);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 } });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const B = 'http://localhost:4177/#';
await p.goto(B + '/login'); await p.waitForSelector('text=Set up local review');
await p.fill('#ls-name', 'Test Admin'); await p.fill('#ls-email', 'qa.admin@example.com'); await p.fill('#ls-pw', 'LocalPass123'); await p.fill('#ls-pw2', 'LocalPass123');
await p.click('button[type=submit]'); await p.waitForSelector('text=Data Import & Validation');
let t = Date.now();
await p.setInputFiles('input[aria-label="Audit export file"]', '/home/claude/research/live.csv');
await p.waitForSelector('text=valid rows', { timeout: 60000 });
console.log('parsed in', Date.now() - t, 'ms;', (await p.locator('text=valid rows').locator('..').textContent()));
await p.check('#imp-pub');
t = Date.now();
await p.click('button:has-text("Import")'); await p.waitForSelector('text=Saved:', { timeout: 120000 });
console.log('imported in', Date.now() - t, 'ms;', await p.locator('text=Saved:').textContent());
await p.waitForTimeout(1500);
await p.reload(); await p.waitForTimeout(1500);
console.log('after reload url', p.url());
t = Date.now();
await p.goto(B + '/'); await p.waitForSelector('text=QA Master Dashboard', { timeout: 60000 }); await p.waitForSelector('text=Consolidated CAM performance', { timeout: 60000 });
console.log('dashboard in', Date.now() - t, 'ms; CAMs', await p.locator('text=CAMs Evaluated').locator('..').textContent());
await p.screenshot({ path: 'e2e/shots/local-dash.png' });
await p.goto(B + '/admin/teams'); await p.waitForTimeout(800);
console.log('teams', await p.locator('main h2').allTextContents());
await p.goto(B + '/admin/emails'); await p.waitForTimeout(1500);
console.log('email page', (await p.locator('text=recipients').first().textContent()));
console.log('errors', errs);
await b.close(); srv.close();
