// Super Admin sets a temporary password; the CAM signs in, must change it, and sees only CAM pages.
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
const root = new URL('../dist-local/', import.meta.url).pathname;
const srv = createServer((q, r) => { let p = join(root, decodeURIComponent(q.url.split('?')[0])); if (!existsSync(p) || p.endsWith('/')) p = join(root, 'index.html');
  r.writeHead(200, { 'content-type': { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html' }[extname(p)] ?? 'application/octet-stream' }); r.end(readFileSync(p)); }).listen(4179);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 } });
await ctx.grantPermissions(['clipboard-read', 'clipboard-write']);
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
const B = 'http://localhost:4179/#';
const ok = (c, m) => { if (!c) { console.log('FAIL', m); process.exitCode = 1; } else console.log('ok  ', m); };
await p.goto(B + '/login'); await p.waitForSelector('text=Set up local review');
await p.fill('#ls-name', 'Test Admin'); await p.fill('#ls-email', 'qa.admin@example.com'); await p.fill('#ls-pw', 'LocalPass123'); await p.fill('#ls-pw2', 'LocalPass123');
await p.click('button[type=submit]'); await p.waitForSelector('text=Data Import');
await p.goto(B + '/admin/users'); await p.waitForSelector('text=Users & Roles');
await p.click('button:has-text("Add user")');
await p.fill('#u-name', 'Test Cam'); await p.fill('#u-email', 'test.cam@example.com'); await p.selectOption('#u-role', 'user');
await p.click('[role=dialog] button:has-text("Save")'); await p.waitForSelector('text=test.cam@example.com');
// before a password: the CAM cannot sign in (and the old shared demo password must not work)
const row = p.locator('tr', { hasText: 'test.cam@example.com' });
ok(await row.locator('text=No login yet').count() === 1, 'new user shows "No login yet"');
ok(await p.locator('tr', { hasText: 'qa.admin@example.com' }).locator('button:has-text("password")').count() === 0, 'no Set password button on own row');
await row.locator('button:has-text("Set password")').click();
const pw = await p.inputValue('#tmp-pw');
ok(pw.length === 14 && /[A-Za-z]/.test(pw) && /\d/.test(pw), 'generated password is strong: ' + pw.replace(/./g, '•'));
await p.click('[role=dialog] button:has-text("Copy")');
ok(await p.evaluate(() => navigator.clipboard.readText()) === pw, 'copy puts it on the clipboard');
await p.click('button:has-text("Save password")'); await p.waitForSelector('text=This is the only time the password is shown');
await p.click('button:has-text("Done")');
ok(await row.locator('text=Login ready').count() === 1, 'row now shows "Login ready" and "Reset password"') ;
ok(await row.locator('button:has-text("Reset password")').count() === 1, 'reset button present');
// the audit log must not contain the password
await p.goto(B + '/admin/audit'); await p.waitForTimeout(800);
ok(!(await p.textContent('body')).includes(pw), 'password not visible in audit log');
const stored = await p.evaluate(async () => { const db = await new Promise(r => { const q = indexedDB.open('csqa-local-review', 1); q.onsuccess = () => r(q.result); });
  return await new Promise(r => { const t = db.transaction('state').objectStore('state').get('state'); t.onsuccess = () => r(JSON.stringify(t.result)); }); });
ok(!stored.includes(pw), 'password not stored in readable form');
// sign out, sign in as CAM
await p.click('button:has-text("Sign out")'); await p.waitForSelector('#login-email');
await p.fill('#login-email', 'test.cam@example.com'); await p.fill('#login-password', 'Demo@2026'); await p.click('button[type=submit]');
await p.waitForTimeout(600); ok((await p.textContent('body')).includes('Incorrect email or password'), 'demo password does not work');
await p.fill('#login-password', pw); await p.click('button[type=submit]');
await p.waitForSelector('text=Set your own password'); ok(true, 'forced to set own password at first sign-in');
await p.goto(B + '/admin/users'); await p.waitForTimeout(500);
ok((await p.textContent('body')).includes('Set your own password'), 'cannot skip the password change');
await p.fill('#reset-pw', 'MyOwnPass2026'); await p.fill('#reset-pw2', 'MyOwnPass2026'); await p.click('button:has-text("Update password")');
await p.waitForSelector('text=Dashboard'); ok(true, 'lands on dashboard after changing');
await p.goto(B + '/admin/users'); await p.waitForTimeout(500);
ok((await p.textContent('body')).includes('You don’t have access to this page'), 'CAM cannot open Users & Roles');
ok(await p.locator('text=QA administration').count() === 0, 'CAM sees no admin menu');
await p.click('button:has-text("Sign out")'); await p.waitForSelector('#login-email');
await p.fill('#login-email', 'test.cam@example.com'); await p.fill('#login-password', pw); await p.click('button[type=submit]');
await p.waitForTimeout(600); ok((await p.textContent('body')).includes('Incorrect email or password'), 'temporary password stops working after change');
await p.fill('#login-password', 'MyOwnPass2026'); await p.click('button[type=submit]'); await p.waitForSelector('text=Dashboard');
ok(!(await p.textContent('body')).includes('Set your own password'), 'own password signs straight in');
ok(errs.length === 0, 'no page errors ' + errs.join('; '));
await b.close(); srv.close();
