// Builds the Google Apps Script project into google/:
//   google/index.html      the whole portal as one page (served by doGet)
//   google/Code.js         the server: access rules, Drive storage, Gmail, Sheets sync, scheduled jobs
//   google/appsscript.json runtime settings (web app runs as the owner, open to the owner's Google Workspace domain)
// Then `npm run google:push` uploads it with clasp.
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'google');
mkdirSync(out, { recursive: true });

// 1. the portal page
if (!process.argv.includes('--server-only')) {
  execSync('npx vite build --mode google', { cwd: root, stdio: 'inherit', env: { ...process.env, VITE_DATA_MODE: 'google' } });
  copyFileSync(join(root, 'dist-google', 'index.html'), join(out, 'index.html'));
}

/** Sheet IDs come from the private .env (never from the public source code). */
function sheetDefines() {
  const env = { ...process.env };
  const file = join(root, '.env');
  if (existsSync(file)) for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^\s*(VITE_[A-Z_]+)\s*=\s*([^#\s]*)/.exec(line);
    if (m && env[m[1]] === undefined) env[m[1]] = m[2];
  }
  const keys = ['VITE_LIVE_SHEET_ID', 'VITE_LIVE_SHEET_GID', 'VITE_ARCHIVE_SHEET_ID'];
  return Object.fromEntries(keys.map((k) => [`import.meta.env.${k}`, JSON.stringify(env[k] || '')]));
}

// 2. the server. Apps Script can't wait for async work, so async/await is compiled to generators and
//    Promise is replaced by a promise that settles immediately (server/syncPromise.ts).
const prelude = await build({
  entryPoints: [join(root, 'server', 'syncPromise.ts')], bundle: true, write: false, format: 'iife', globalName: '__CSQA_SYNC',
  target: 'es2020', platform: 'neutral', logLevel: 'error',
});
const server = await build({
  entryPoints: [join(root, 'server', 'main.ts')], bundle: true, write: false, format: 'iife', globalName: '__CSQA',
  target: 'es2020', platform: 'neutral', supported: { 'async-await': false, 'async-generator': false, 'for-await': false },
  define: { 'import.meta.env.VITE_DATA_MODE': '"google"', ...sheetDefines() }, logLevel: 'error', legalComments: 'none',
});
const code = [
  '// CS QA Portal — Google Apps Script server. Generated by scripts/build-google.mjs; edit server/*.ts instead.',
  prelude.outputFiles[0].text,
  'var Promise = __CSQA_SYNC.SyncPromise;',
  server.outputFiles[0].text,
  // Apps Script needs top-level functions for the web app, google.script.run and triggers.
  'function doGet(e) { return __CSQA.doGet(e); }',
  'function api(payload) { return __CSQA.api(payload); }',
  'function scheduledJobs() { return __CSQA.scheduledJobs(); }',
  'function authorize() { return __CSQA.authorize(); }',
  '',
].join('\n');
if (/\bawait\b\s|async\s+(function|\()/.test(server.outputFiles[0].text.replace(/"[^"\n]*"|'[^'\n]*'|`[^`]*`/g, ''))) {
  console.warn('warning: async code left in the server bundle');
}
writeFileSync(join(out, 'Code.js'), code);

// 3. manifest
const domainOnly = process.env.GOOGLE_ACCESS !== 'ANYONE';
writeFileSync(join(out, 'appsscript.json'), JSON.stringify({
  timeZone: 'Asia/Kolkata',
  runtimeVersion: 'V8',
  exceptionLogging: 'STACKDRIVER',
  dependencies: { enabledAdvancedServices: [{ userSymbol: 'Drive', serviceId: 'drive', version: 'v3' }, { userSymbol: 'Sheets', serviceId: 'sheets', version: 'v4' }] },
  webapp: { executeAs: 'USER_DEPLOYING', access: domainOnly ? 'DOMAIN' : 'ANYONE' },
  oauthScopes: [
    'https://www.googleapis.com/auth/drive',                 // the portal's private data folder (+ Drive API for saving)
    'https://www.googleapis.com/auth/spreadsheets.readonly', // read the audit sheets
    'https://www.googleapis.com/auth/script.send_mail',      // weekly reports and appeal notifications
    'https://www.googleapis.com/auth/script.scriptapp',      // the 30-minute scheduled job
    'https://www.googleapis.com/auth/userinfo.email',        // who is signed in
  ],
}, null, 2) + '\n');

if (!existsSync(join(out, '.claspignore'))) writeFileSync(join(out, '.claspignore'), '**/**\n!Code.js\n!index.html\n!appsscript.json\n');
const kb = (f) => Math.round(readFileSync(join(out, f)).length / 1024);
console.log(`\nGoogle Apps Script project ready in google/  (index.html ${kb('index.html')} KB, Code.js ${kb('Code.js')} KB)`);
