// Generates supabase/migrations/..._reference_data.sql from the shared rubric.
// Run: node scripts/gen-reference-sql.ts
import { writeFileSync } from 'node:fs';
import { TASK_TYPES, PARAMETERS, DEFAULT_SETTINGS, SETTING_DESCRIPTIONS } from '../supabase/functions/_shared/rubric.ts';

const q = (s: string | null) => (s === null ? 'null' : `'${s.replace(/'/g, "''")}'`);
const lines: string[] = [
  '-- GENERATED by scripts/gen-reference-sql.ts from supabase/functions/_shared/rubric.ts — do not edit by hand.',
  '-- Reference data: task types, scoring parameters (live audit form weights) and default settings.',
  '',
];
for (const t of TASK_TYPES) {
  lines.push(`insert into public.task_types (code, name, source_label, feedback_column, fcr_column, sort_order) values (${q(t.code)}, ${q(t.name)}, ${q(t.sourceLabel)}, ${q(t.feedbackColumn)}, ${q(t.fcrColumn)}, ${t.sortOrder}) on conflict (code) do nothing;`);
}
lines.push('');
for (const p of PARAMETERS) {
  const aliases = `array[${(p.aliases ?? []).map(q).join(', ')}]::text[]`;
  lines.push(`insert into public.evaluation_parameters (id, task_type, name, section, max_score, sort_order, source_column, source_aliases, rubric_version, active) values (${q(p.id)}, ${q(p.taskType)}, ${q(p.name)}, ${q(p.section)}, ${p.maxScore}, ${p.sortOrder}, ${q(p.sourceColumn)}, ${aliases}, ${q(p.rubricVersion ?? 'current')}, ${p.active === false ? 'false' : 'true'}) on conflict (id) do nothing;`);
}
lines.push('');
for (const [k, v] of Object.entries(DEFAULT_SETTINGS)) {
  lines.push(`insert into public.settings (key, value, description) values (${q(k)}, ${q(JSON.stringify(v))}::jsonb, ${q(SETTING_DESCRIPTIONS[k as keyof typeof SETTING_DESCRIPTIONS])}) on conflict (key) do nothing;`);
}
writeFileSync(new URL('../supabase/migrations/20260929000004_reference_data.sql', import.meta.url), lines.join('\n') + '\n');
console.log('reference SQL written');
